# Generated by potato — do not edit; regenerated on install and update.
potato() {
  if [ $# -gt 0 ]; then
    "/POTATO/bin/potato" "$@"
    return $?
  fi
  local __potato_out __potato_cmd __potato_status
  __potato_out="$(mktemp "${TMPDIR:-/tmp}/potato.XXXXXX")" || return 1
  "/POTATO/bin/potato" --out "$__potato_out"
  __potato_status=$?
  __potato_cmd="$(cat "$__potato_out" 2>/dev/null)"
  rm -f "$__potato_out"
  [ "$__potato_status" -ne 0 ] && return "$__potato_status"
  [ -n "$__potato_cmd" ] && print -z -- "$__potato_cmd"
  return 0
}
