# Generated by potato — do not edit; regenerated on install and update.
__potato_fill() {
  READLINE_LINE="$__POTATO_CMD"
  READLINE_POINT=${#READLINE_LINE}
  __POTATO_CMD=""
}
potato() {
  if [ $# -gt 0 ]; then
    "/POTATO/bin/potato" "$@"
    return $?
  fi
  local __potato_out __potato_cmd __potato_status
  __potato_out="$(mktemp "${TMPDIR:-/tmp}/potato.XXXXXX")" || return 1
  "/POTATO/bin/potato" --out "$__potato_out"
  __potato_status=$?
  __potato_cmd="$(cat "$__potato_out" 2>/dev/null)"
  rm -f "$__potato_out"
  [ "$__potato_status" -ne 0 ] && return "$__potato_status"
  [ -z "$__potato_cmd" ] && return 0
  if [ "${BASH_VERSINFO[0]:-0}" -ge 4 ]; then
    __POTATO_CMD="$__potato_cmd"
    bind -x '"\e[0n": __potato_fill' 2>/dev/null
    printf '\e[5n'
  else
    # bash < 4 cannot pre-fill the prompt; print the command instead
    printf '%s\n' "$__potato_cmd"
  fi
}
