// Shell glue (spec §4.1, §6.2). The installed wrapper function *is* the
// `potato` command: it invokes the binary by absolute path (no PATH edit) and
// carries the selection back via a mktemp --out file — empty file = cancelled.
// zsh pre-fills with `print -z`; bash with a `bind -x` widget triggered by a
// DSR round-trip (\e[5n → terminal replies \e[0n at the next prompt), which
// keeps arbitrary command text out of readline macro quoting.

import { writeFileSync } from 'node:fs';
import { initPath } from './paths';

export function initScript(shell: 'zsh' | 'bash' | 'sh', bin: string, dir: string): string {
  switch (shell) {
    case 'zsh':
      return `# Generated by potato — do not edit; regenerated on install and update.
potato() {
  if [ $# -gt 0 ]; then
    "${bin}" "$@"
    return $?
  fi
  local __potato_out __potato_cmd __potato_status
  __potato_out="$(mktemp "\${TMPDIR:-/tmp}/potato.XXXXXX")" || return 1
  "${bin}" --out "$__potato_out"
  __potato_status=$?
  __potato_cmd="$(cat "$__potato_out" 2>/dev/null)"
  rm -f "$__potato_out"
  [ "$__potato_status" -ne 0 ] && return "$__potato_status"
  [ -n "$__potato_cmd" ] && print -z -- "$__potato_cmd"
  return 0
}
`;
    case 'bash':
      return `# Generated by potato — do not edit; regenerated on install and update.
__potato_fill() {
  READLINE_LINE="$__POTATO_CMD"
  READLINE_POINT=\${#READLINE_LINE}
  __POTATO_CMD=""
}
potato() {
  if [ $# -gt 0 ]; then
    "${bin}" "$@"
    return $?
  fi
  local __potato_out __potato_cmd __potato_status
  __potato_out="$(mktemp "\${TMPDIR:-/tmp}/potato.XXXXXX")" || return 1
  "${bin}" --out "$__potato_out"
  __potato_status=$?
  __potato_cmd="$(cat "$__potato_out" 2>/dev/null)"
  rm -f "$__potato_out"
  [ "$__potato_status" -ne 0 ] && return "$__potato_status"
  [ -z "$__potato_cmd" ] && return 0
  if [ "\${BASH_VERSINFO[0]:-0}" -ge 4 ]; then
    __POTATO_CMD="$__potato_cmd"
    bind -x '"\\e[0n": __potato_fill' 2>/dev/null
    printf '\\e[5n'
  else
    # bash < 4 cannot pre-fill the prompt; print the command instead
    printf '%s\\n' "$__potato_cmd"
  fi
}
`;
    case 'sh':
      return `# Generated by potato — sources the right integration for this shell.
if [ -n "$ZSH_VERSION" ]; then
  . "${dir}/init.zsh"
elif [ -n "$BASH_VERSION" ]; then
  . "${dir}/init.bash"
fi
`;
  }
}

// Regenerate all three init files next to the binary's data dir — run by the
// installer and after every `potato update` binary swap (spec §6.2, §8).
export function writeInitFiles(bin: string, dir: string): void {
  for (const shell of ['zsh', 'bash', 'sh'] as const) {
    writeFileSync(initPath(shell), initScript(shell, bin, dir));
  }
}
